//<!--
//1@@m3

function TaaSDynamic(){var Cookies=window['cookies-browser']||raptor.require('ebay.cookies');this.readCookie=function(cookie,cookielet){var cookieValue=Cookies.readCookie(cookie,cookielet);return cookieValue;};this.writeCookielet=function(cookie,cookielet,value,expDateCookielet,expDateCookie){Cookies.writeCookielet(cookie,cookielet,value,expDateCookielet,expDateCookie);};this.sendRequestForIdMap=function(psUrl,pfCallback,poScope,psCallbackParam,pbSendResponseOnLoad){var url=psUrl;if(url.indexOf('?')>-1){url+='&';}else{url+='?';}
url+=psCallbackParam+'=TaaSIdMapTrackerObj.handleResponse';$.ajax({url:encodeURI(url),dataType:'jsonp',jsonp:false});};this.readMultiLineCookie=function(cookie,cookielet){Cookies.readMultiLineCookie(cookie,cookielet);};this.writeMultiLineCookie=function(cookie,cookielet,value,exp,contExp){Cookies.writeMultiLineCookie(cookie,cookielet,value,exp,contExp);};this.writeCookie=function(cookie,value,expDateCookie){Cookies.writeCookie(cookie,value,expDateCookie);};}
var TaaSDynamicObj=new TaaSDynamic();(function(){'use strict';var getElem=function(elem){if(typeof(elem)==='string'){return $(document.getElementById(elem.match(/^#?(.*)/)[1])||elem);}else{return(elem&&elem.jquery)?elem:$(elem);}},bind=function(scope,elem,type,func,data){return((elem=getElem(elem))&&elem.length)?elem.bind(type,data,$.proxy(func,scope)):elem;},_extend=function(target){for(var i=1;i<arguments.length;i++){var source=arguments[i];for(var key in source){if(Object.prototype.hasOwnProperty.call(source,key)){target[key]=source[key];}}}
return target;};var Tracker=function(config){var self=this;_extend(self,self.config=config);self.image=$('<img/>').css('display','none');if(self.rover.sync)self.image.attr('src',self.rover.sync);bind(self,document,'click',self.onBody);bind(self,document,'mousedown',self.onMouse);bind(self,document,'rover',self.onRover);bind(self,document,'track',self.onTrack);bind(self,document,'pulsar',self.onPulsar);self.originalPSI=self.currentPSI=config.psi;$('body').bind("TRACKING_UPDATE_PSI",function(e,m){if(m&&m.psi){self.currentPSI=m.psi;}
if(m&&m.callback&&typeof(m.callback)=="function"){m.callback.call(self);}});$('body').bind("ADD_LAYER_PSI",function(e,m){if(m&&m.psi){self.currentPSI=self.currentPSI+m.psi;}});$('body').bind("CLEAR_LAYER_PSI",function(e){self.currentPSI=self.originalPSI;});};_extend(Tracker.prototype,{codes:['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','-','_','!'],sizes:{'p':4,'c':1,'m':3,'l':3},start:{'p':1,'c':5,'m':6,'l':9},target:function(click){return(click.tagName)?click:click.target;},attrib:function(target,name){return target.getAttribute?target.getAttribute(name):null;},valid:function(tag,href){return(href&&(href.indexOf('.ebay.')>0))?tag:null;},trackable:function(target){var self=this,tag=target.tagName;if(tag.match(/^a$|area/i))return self.valid(tag,tag.href);else if(tag.match(/input/)&&tag.type.match(/submit/i)&&tag.form)return self.valid(tag,form.action);else return null;},click:function(click){var self=this,target=self.target(click);for(var trackable=null;(target&&target.tagName);target=target.parentNode){trackable=trackable||self.trackable(target);if(self.attrib(target,'_sp'))return self.clickElement(target,trackable);}
if(self.pid)self.track(self.pid);},clickElement:function(element,trackable){var self=this,trkinfo=self.attrib(element,'_sp');self.track(trkinfo.split(';')[0],trackable?self.attrib(trackable,'_l'):null);},track:function(trksid,trklid){var self=this,terms=trksid.split('.');if(!trksid.match(/p\d+/))terms.push(self.pid);if(trklid)terms.push(trklid);var cookie=TaaSDynamicObj.readCookie('ds2','sotr');var chars=self.chars((cookie&&(cookie.charAt(0)=='b'))?cookie:'bzzzzzzzzzzz');for(var idx=0,len=terms.length;(idx<len);idx++){var match=terms[idx].match(/([pcml])(\d+)/);if(match==null)continue;var key=match[1],value=match[2];var size=self.sizes[key],start=self.start[key];var encoded=self.chars(self.encode(value,size));for(var sdx=0;(sdx<size);sdx++)chars[start+sdx]=encoded[sdx];}
var idx=0,len=chars.length,cookie='';while(idx<len)cookie=cookie.concat(chars[idx++]);TaaSDynamicObj.writeCookielet('ds2','sotr',cookie);},chars:function(cookie){var idx=0,len=cookie.length,chars=[];while(idx<len)chars.push(cookie.charAt(idx++));return chars;},encode:function(num,size){for(var codes=this.codes,encoded='';(num>=64);num=num/64|0)encoded=codes[num%64]+encoded;encoded=((num>=0)?codes[num]:'')+encoded;return encoded.concat('zzzz').substring(0,size);},onBody:function(event){this.click(event);},onMouse:function(event){TaaSDynamicObj.writeCookielet('ebay','psi',this.currentPSI);},onTrack:function(event,object){var trksid=object.trksid;if(trksid)this.track(trksid,object.trklid);},onRover:function(event,inputArgs){if(!inputArgs||typeof inputArgs!=='object'){return;}
var self=this;var imp=inputArgs.imp;var href=self.rover.uri+(imp?self.rover.imp:self.rover.clk);var trkQueryString;var impQueryString;delete inputArgs.imp;if(imp){impQueryString=obj2kvp(imp,'&',true);}
if(inputArgs){inputArgs.ts=Date.now();trkQueryString=obj2kvp(inputArgs,'&',true);}
if(trkQueryString&&trkQueryString.length>0){href+=(href.indexOf('?')<0?'?':'&')+'trknvp='+trkQueryString;}
if(impQueryString&&impQueryString.length>0){href+=(href.indexOf('?')<0?'?':'&')+'imp='+impQueryString;}
self.image.attr('src',(href));},onPulsar:function(event,trackingObjInp,actionKindObjInp){if(typeof _plsUBTTQ!=='undefined'&&typeof trackingObjInp!=='undefined'&&trackingObjInp!=null){var trackingObj=(JSON.parse(JSON.stringify(trackingObjInp)));var properties=trackingObj.eventProperty;if(typeof actionKindObjInp!=='undefined'&&actionKindObjInp!=null){var actionKindObj=(JSON.parse(JSON.stringify(actionKindObjInp)));if(typeof properties!=='undefined'&&properties!=null){properties.actionKind=actionKindObj.actionKind;}}
if(trackingObj.eventFamily!=null&&trackingObj.eventAction!=null){_plsUBTTQ.push(['customEvts',trackingObj.eventFamily,trackingObj.eventAction,properties]);}}}});window.TaaSTrackingCore=Tracker;function obj2kvp(input,delimiter,canEncodeUriComponent){if(input&&typeof input==='object'){var result=[];Object.keys(input).forEach(function forEach(key){result.push(key+'='+input[key]);});var resultStr=result.join(delimiter||',');return canEncodeUriComponent?encodeURIComponent(resultStr):resultStr;}else{return canEncodeUriComponent?encodeURIComponent(input):input;}}})();function TaaSIdMapTracker(){var url;this.roverService=function(roverUrl){if(window.location.protocol=="https:"||!roverUrl||TaaSDynamicObj.readCookie("dp1","idm")){return;}
this.url=roverUrl;document.onload=this.sendRequest();};this.sendRequest=function(){TaaSDynamicObj.sendRequestForIdMap(this.url,this.handleResponse,this,'cb',false);};this.setCookieExpiration=function(date){if(typeof date=='number'&&date>0){TaaSDynamicObj.writeCookielet("dp1","idm",'1',date/86400,'');}};this.handleResponse=function(content){if(content&&content.length>1){var arrlen=content.length-1;for(var i=0;i<arrlen;i++){this.createImage(content[i]);}
this.setCookieExpiration(content[arrlen]);}};this.createImage=function(imgSrc){if(imgSrc&&imgSrc.length>1){var image=document.createElement("IMG");image.width="1";image.height="1";image.src=imgSrc;image.alt="";document.body.appendChild(image);}};}
var TaaSIdMapTrackerObj=new TaaSIdMapTracker();function TaaSIdMapTracker(){var url;this.roverService=function(roverUrl){if(window.location.protocol=="https:"||!roverUrl||TaaSDynamicObj.readCookie("dp1","idm")){return;}
this.url=roverUrl;document.onload=this.sendRequest();};this.sendRequest=function(){TaaSDynamicObj.sendRequestForIdMap(this.url,this.handleResponse,this,'cb',false);};this.setCookieExpiration=function(date){if(typeof date=='number'&&date>0){TaaSDynamicObj.writeCookielet("dp1","idm",'1',date/86400,'');}};this.handleResponse=function(content){if(content&&content.length>1){var arrlen=content.length-1;for(var i=0;i<arrlen;i++){this.createImage(content[i]);}
this.setCookieExpiration(content[arrlen]);}};this.createImage=function(imgSrc){if(imgSrc&&imgSrc.length>1){var image=document.createElement("IMG");image.width="1";image.height="1";image.src=imgSrc;image.alt="";document.body.appendChild(image);}};}
// b=18006650 -->